#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/telemost/telemost /usr/bin/telemost

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/telemost.service ]; then
			rm /etc/systemd/system/telemost.service /usr/lib/systemd/system/telemost.service /usr/lib/systemd/user/telemost.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/telemost/files/systemd/telemost.service /usr/lib/systemd/system/telemost.service
		# try fix error in Ubuntu 18.04
		# Failed to reload telemost.service: Unit telemost.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/telemost.service:10: Executable path is not absolute: pkill -f "telemost --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/telemost.service
		fi
		systemctl daemon-reload
		systemctl enable telemost
		systemctl start telemost
	fi
fi
