set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_OSX_ARCHITECTURES arm64)

if(DEFINED ENV{GITHUB_WORKSPACE})
    set(VCPKG_C_FLAGS "-ffile-prefix-map=$ENV{GITHUB_WORKSPACE}=.")
    set(VCPKG_CXX_FLAGS "-ffile-prefix-map=$ENV{GITHUB_WORKSPACE}=.")
endif()
